import { PDFDocument } from "pdf-lib";
import { embedInvoicePdfFonts } from "@/lib/pdf/font-cache";
import { PAYMENT_METHOD_LABELS, type ZReportPayload } from "@/lib/finance/document-payload";
import { parseNum } from "@/lib/format-shekel";

export const VAT_RATE = 0.18;

export const FOOTER_TEXT = "Generated by WEGO ERP SYSTEM";

export function safeFilePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]+/g, "")
    .replace(/\s+/g, "_")
    .slice(0, 80);
}

export function vatLabel(vatType: string | null): string {
  if (vatType === "before_vat") return "ללא מע״מ";
  if (vatType === "exempt") return "פטור ממע״מ";
  return "כולל מע״מ";
}

export function paymentMethodLabel(method: string | null): string {
  if (!method) return "—";
  return PAYMENT_METHOD_LABELS[method as keyof typeof PAYMENT_METHOD_LABELS] ?? method;
}

export async function loadHebrewFont(pdfDoc: PDFDocument) {
  const fonts = await embedInvoicePdfFonts(pdfDoc);
  return fonts.he;
}

export async function loadInvoicePdfFonts(pdfDoc: PDFDocument) {
  return embedInvoicePdfFonts(pdfDoc);
}

export function zReportTotals(z: ZReportPayload): {
  cashSum: number;
  creditSum: number;
  grand: number;
} {
  const cashSum = z.cashTaxable + z.cashExempt;
  const creditSum = z.creditTaxable + z.creditExempt;
  const grand = cashSum + creditSum + z.transfers;
  return { cashSum, creditSum, grand };
}
